fileObject = open("#1", "w")
fileObject.write("Hydrogen\n")
fileObject = open("#2", "w")
fileObject.write("Helium\n")
fileObject = open("#3", "w")
fileObject.write("Lithium\n")
fileObject = open("#4", "w")
fileObject.write("Beryllium\n")
fileObject = open("#5", "w")
fileObject.write("Boron\n")
fileObject = open("#6", "w")
fileObject.write("Carbon\n")
fileObject = open("#7", "w")
fileObject.write("Nitrogen\n")
fileObject = open("#8", "w")
fileObject.write("Oxygen\n")
fileObject = open("#9", "w")
fileObject.write("Fluorine\n")
fileObject = open("#10", "w")
fileObject.write("Neon\n")
